-- ============================================================
-- Migration 032: Fix Amazon Agent Account Lookup in rpc_pairing_poll
-- ============================================================
-- Problem: Amazon agents have account_id = NULL (they link via ebay_agent_id)
-- The rpc_pairing_poll function was querying account by v_agent.account_id
-- which returns NULL for Amazon agents, causing blank account display.
--
-- Fix: Query account through the ebay_agent_id chain for Amazon agents.
-- Note: Uses explicit column selection to avoid row type caching issues.
-- ============================================================

DROP FUNCTION IF EXISTS public.rpc_pairing_poll(TEXT);

CREATE OR REPLACE FUNCTION public.rpc_pairing_poll(
  p_install_instance_id TEXT
) RETURNS TABLE (
  status TEXT,
  agent_id UUID,
  install_token TEXT,
  role TEXT,
  label TEXT,
  account_name TEXT,
  rejection_reason TEXT,
  expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_request_id UUID;
  v_request_status TEXT;
  v_request_expires_at TIMESTAMPTZ;
  v_request_rejection_reason TEXT;

  v_agent_id UUID;
  v_agent_role TEXT;
  v_agent_label TEXT;
  v_agent_token_secret TEXT;
  v_agent_account_id UUID;
  v_agent_ebay_agent_id UUID;

  v_ebay_agent_account_id UUID;
  v_account_name TEXT;
  v_account_code TEXT;

  v_now TIMESTAMPTZ := NOW();
BEGIN
  -- Find most recent request for this device
  SELECT r.id, r.status, r.expires_at, r.rejection_reason
  INTO v_request_id, v_request_status, v_request_expires_at, v_request_rejection_reason
  FROM public.automation_pairing_requests r
  WHERE r.install_instance_id = p_install_instance_id
  ORDER BY r.created_at DESC
  LIMIT 1;

  IF v_request_id IS NULL THEN
    RETURN QUERY SELECT 'not_found'::TEXT, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  -- Check if expired (pending request past expiration)
  IF v_request_status = 'pending' AND v_request_expires_at <= v_now THEN
    UPDATE public.automation_pairing_requests SET status = 'expired', updated_at = v_now WHERE id = v_request_id;
    RETURN QUERY SELECT 'expired'::TEXT, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, v_request_expires_at;
    RETURN;
  END IF;

  -- Handle different statuses
  IF v_request_status = 'pending' THEN
    RETURN QUERY SELECT 'pending'::TEXT, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, v_request_expires_at;
    RETURN;
  ELSIF v_request_status = 'rejected' THEN
    RETURN QUERY SELECT 'rejected'::TEXT, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, v_request_rejection_reason, NULL::TIMESTAMPTZ;
    RETURN;
  ELSIF v_request_status = 'expired' THEN
    RETURN QUERY SELECT 'expired'::TEXT, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, v_request_expires_at;
    RETURN;
  ELSIF v_request_status = 'approved' THEN
    -- Find the agent created for this request (explicit columns to avoid row type caching)
    SELECT a.id, a.role, a.label, a.token_secret, a.account_id, a.ebay_agent_id
    INTO v_agent_id, v_agent_role, v_agent_label, v_agent_token_secret, v_agent_account_id, v_agent_ebay_agent_id
    FROM public.automation_agents a
    WHERE a.install_instance_id = p_install_instance_id AND a.status = 'active'
    ORDER BY a.created_at DESC
    LIMIT 1;

    IF v_agent_id IS NULL THEN
      RETURN QUERY SELECT 'pending'::TEXT, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, v_request_expires_at;
      RETURN;
    END IF;

    -- Get account name from existing accounts table
    -- For eBay agents: direct link via account_id
    -- For Amazon agents: indirect link via ebay_agent_id → ebay_agent.account_id
    IF v_agent_role = 'AMAZON_AGENT' AND v_agent_ebay_agent_id IS NOT NULL THEN
      -- Amazon agent: get account through eBay agent
      SELECT ea.account_id INTO v_ebay_agent_account_id
      FROM public.automation_agents ea
      WHERE ea.id = v_agent_ebay_agent_id;

      IF v_ebay_agent_account_id IS NOT NULL THEN
        SELECT acc.name, acc.account_code INTO v_account_name, v_account_code
        FROM public.accounts acc
        WHERE acc.id = v_ebay_agent_account_id;
      END IF;
    ELSE
      -- eBay agent or other: direct account lookup
      SELECT acc.name, acc.account_code INTO v_account_name, v_account_code
      FROM public.accounts acc
      WHERE acc.id = v_agent_account_id;
    END IF;

    -- Update last_seen_at
    UPDATE public.automation_agents SET last_seen_at = v_now WHERE id = v_agent_id;

    -- Return agent info (token generated by API layer with token_secret)
    RETURN QUERY SELECT
      'approved'::TEXT,
      v_agent_id,
      v_agent_token_secret,
      v_agent_role,
      v_agent_label,
      COALESCE(v_account_name, v_account_code),
      NULL::TEXT,
      NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  -- Fallback
  RETURN QUERY SELECT v_request_status, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT, v_request_expires_at;
END;
$$;

-- Lock down execution privileges
REVOKE ALL ON FUNCTION public.rpc_pairing_poll(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rpc_pairing_poll(TEXT) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_pairing_poll(TEXT) TO service_role;

-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
